# 搴旂敤鐗堟湰锛堝彂甯冩椂閫掑 versionCode锛屾洿鏂?versionName锛?
VERSION_CODE=8
VERSION_NAME=3.4

org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g
org.gradle.daemon=true
org.gradle.parallel=true
android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
kotlin.compiler.execution.strategy=in-process

