# App version
VERSION_CODE=23
VERSION_NAME=4.0

org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=2g
org.gradle.daemon=true
org.gradle.parallel=true
android.useAndroidX=true
android.nonTransitiveRClass=true
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
android.r8.strictFullModeForKeepRules=false
kotlin.compiler.execution.strategy=in-process
